---
- hosts: all
  become_user: dcoker
  tasks:
    - name: determine swarm status
      shell: >
        docker info | egrep '^Swarm' | cut -d ' ' -f2 
      register: result
      ignore_errors: True
    - name: Ansible shell register result
      debug: msg="{{ result.stdout_lines }}"
