---
- hosts: worker-nodes
  gather_facts: False
#    # vars:
#      #   - MyMessage: "Welcome to Ansible World!!"
  vars_files:
    - 'vars.yml'
#
  become: yes
  tasks:
    - name: check datadog-agent status for unhealthy state
      become: true
      shell: docker ps | grep datadog-agent | grep -o '(unhealthy)'
      register: output
      ignore_errors: True
#    - debug: msg="{{output.stdout}}"
    - name: Restart datadog-agent when unhealthy state
#      become: true
      shell: docker restart datadog-agent
      #shell: echo "hello"
      when: output.stdout == "(unhealthy)"
      register: out
      ignore_errors: True
#    - debug: msg="{{out.stdout}}"

    - name: check datadog-agent status for exited state
      become: true
      shell: docker ps -a --filter "name=datadog-agent" | awk '{print $7}' | grep -o 'Exited'
      register: output
      ignore_errors: True
#    - debug: msg="{{output.stdout}}"
    - name: Start datadog-agent when exited state
#      become: true
      shell: docker start datadog-agent
      #shell: echo "hello"
      when: output.stdout == "Exited"
      register: out
      ignore_errors: True
