---
- hosts: firstmanager
  become: yes
  become_method: sudo
  tasks:
    - name: Retrieving swarm manager token
      shell: docker swarm join-token -q worker
      register: swarm_worker_token
      ignore_errors: True
    - name: Ansible shell register output
      debug: msg={{ swarm_worker_token.stdout_lines }}

- hosts: workers
  become: yes
  become_method: sudo     
  vars_prompt:
    - name: firstmanager
      prompt: "Enter Leader Managers Host IP address:"
  vars:
    token: "{{ hostvars[groups['firstmanager'][0]]['swarm_worker_token']['stdout'] }}"
    
  tasks:
    - name: Determine swarm status
      shell:
        docker info | egrep '^Swarm' | cut -d ' ' -f2 | egrep -w active
      register: output
      ignore_errors: True
    - name: Ansible shell register output
      debug: msg={{ output.rc }}
    - name: Joining Workers to Swarm
      shell: 
         docker swarm join --token {{ token }} {{ firstmanager }}:2377
      when: output.rc == 1