---
- hosts: servers
  become: yes
  become_method: sudo
  tasks:
    - name: Determine swarm status
      shell:
        docker info | egrep '^Swarm' | cut -d ' ' -f2
      register: output
      ignore_errors: True
    - name: Output
      debug: msg={{ output.stdout_lines }}
    