---
- hosts: firstmanager
  become: yes
  become_method: sudo
  vars_prompt:
    - name: firstmanager
      prompt: "Enter Leader Managers Host IP address:"
      private: No
    - name: adminpassword
      prompt: "Enter the UCP admin password:"
  tasks:
    - name: Creating First UCP Manager
      shell:
        docker container run --rm -it --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp:2.2.14 install --host-address {{ firstmanager }} --admin-username admin --admin-password {{ adminpassword }} --san ucpdr.qloudableincdr.com > ucp.log 2>&1
    - name: Display Logs
      shell: 
        cat ucp.log
      register: output
      ignore_errors: True
    - name: Output
      debug: msg={{ output.stdout_lines }}