---
- hosts: servers
  become: yes
  become_method: sudo
  tasks:
    - name: iptables_flush
      shell:
        iptables -F
      register: output
      ignore_errors: True
    - name: Output
      debug: msg={{ output.stdout_lines }}