---
- hosts: nodes
  connection: ssh
  gather_facts: False
  vars_files:
   - 'vars.yml'
  become: yes
  tasks:
   - name: OSKernelCheck
     become: yes
     shell: name=`hostnamectl | sed -n 's/.*Static //p'`; os_version=`hostnamectl | sed -n 's/.*Ubuntu //p'`; kernel_version=`hostnamectl | sed -n 's/.*Linux //p'`; echo Current OS Version $os_version , Current Kernel version  $kernel_version; if  [ $kernel_version != 4.15.0-1018-oracle ] && [ $kernel_version != Linux 4.15.0-1021-oracle ] || [ $os_version != 18.04.3 LTS ]; then echo $name Os or kernel version not matching; exit 1; fi
     register: output
