---
- hosts: all
  gather_facts: False
#    # vars:
#      #   - MyMessage: "Welcome to Ansible World!!"
  vars_files:
    - 'vars.yml'
#
  become: yes
  tasks:
    - name: List root Permissions
      become: true
      command: grep -Po '^sudo.+:\K.*$' /etc/group
      register: output
    - debug: var=output.stdout_lines

