---
- hosts: firstmanager
  become_user: docker
  tasks:
    - name: see if backup file is there
      shell: >
        ls -ltr /home/QLOUDABLEINC/docker/backupNPR.tar
      register: result
      ignore_errors: True
    - name: back up previous backfiles
      shell: >
         mv /home/QLOUDABLEINC/docker/backupNPR.tar /home/QLOUDABLEINC/docker/backupNPR.tar.old
      when: result.rc == 0

    - name: backup ucp manager
      shell: >
       docker container run 
       --log-driver none --rm -i --name ucp 
       -v /var/run/docker.sock:/var/run/docker.sock docker/ucp backup 
       --id okbi4f4mtbm15khvlvgmwzmqq > /home/QLOUDABLEINC/docker/backupNPR.tar

    - name: check for the tar file
      shell: >
       ls -ltr /home/QLOUDABLEINC/docker/backupNPR.tar
      register: backupfile

    - debug: msg="{{  backupfile.stdout_lines }}"


