---
- hosts: firstmanager
  become_user: docker
  tasks:
    - name: see if backup file is there
      shell: >
        ls -ltr /home/QLOUDABLEINC/docker/backupPRD.tar
      register: result
      ignore_errors: True
    - name: back up previous backfiles
      shell: >
         mv /home/QLOUDABLEINC/docker/backupPRD.tar /home/QLOUDABLEINC/docker/backupPRD.tar.old
      when: result.rc == 0

    - name: backup ucp manager
      shell: >
       docker container run
       --log-driver none --rm -i --name ucp
       -v /var/run/docker.sock:/var/run/docker.sock docker/ucp backup
       --id uh4amke1v8f5qzuya48dc47v5 > /home/QLOUDABLEINC/docker/backupPRD.tar

    - name: check for the tar file
      shell: >
       ls -ltr /home/QLOUDABLEINC/docker/backupPRD.tar
      register: backupfile

    - debug: msg="{{  backupfile.stdout_lines }}"

