---
- hosts: all
  become_user: docker
  tasks:
    - name: swarm leave command
      shell: >
       docker swarm leave --force
    - name: remove all containers
      shell: >
       docker ps -a -q | xargs docker rm --force

