---
- hosts: okerdbnodes
  connection: ssh
  gather_facts: False
  vars_files:
   - 'vars.yml'
  become: yes
  tasks:
   - name: RDB config check
     become: yes
     script: ./scripts/rdb-configcheck.sh
     register: output
     failed_when: '"error" in output.stdout'
   - debug: var=output
