---
- hosts: oke-rdb-nodes
  connection: ssh
  gather_facts: False
  vars_files:
    - 'vars.yml'
  become: yes
  tasks:
    - name: testing echo statement
      shell: echo testing 
    - name: testing script
      become: yes
      script: /data01/jenkins/workspace/infra-testing/infra-ansible/ansible/playbooks/scripts/test.sh
#       register: output
#       failed_when: '"Error" in output.stdout'
#     - debug: var=output
