---
- hosts: dtr01
  become: true
  tasks:
    - name: get the ca certs
      shell: >
        curl -k https://192.168.99.101/ca -o /home/QLOUDABLEINC/docker/ca.pem

    - name: restore the first ucp manager
      shell: >
       docker container run --rm -i  
        docker/dtr:2.4.3 restore
        --ucp-url https://ucplb.qloudableinc.com
        --ucp-ca "$( cat /home/QLOUDABLEINC/docker/ca.pem }"
        --ucp-username admin
        --ucp-password Qloud@ble!!
        --ucp-node "$( hostname )"
        --dtr-external-url https://dtrlb.qloudableinc.com < /home/QLOUDABLEINC/docker/backup-metadata.tar
       < /home/QLOUDABLEINC/docker/backupNPR.tar
    - name: Wait port 443 to become open on the host, don't start checking for 10 seconds
      wait_for:
         port: 443
         delay: 10

