---
- hosts: firstmanager
  become_user: docker
  tasks:
    - name: restore the first ucp manager
      shell: >
       docker container run --rm -i --name ucp 
       -v /var/run/docker.sock:/var/run/docker.sock docker/ucp:2.2.5 restore 
       < /home/QLOUDABLEINC/docker/backupNPR.tar
    - name: Wait port 443 to become open on the host, don't start checking for 10 seconds
      wait_for:
         port: 443
         delay: 10

