---
- hosts: jenkins-node 
  connection: ssh
  gather_facts: False
  vars_files:
    - 'vars.yml'
  become: yes
  tasks:
    - name: testing 
      become: yes
      script: ./playbooks/scripts/test.sh
      register: output
      failed_when: '"Error" in output.stdout'
    - debug: var=output