Notification-MicroService notification https://oci-dl-pi-notification.qloudable-npr.com/swagger
Marketplace-service       marketplace  https://oci-dl-pi-marketplace.qloudable-npr.com/v2/components/marketplace-service/swagger
